apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1
        readinessprobe:
         tcpsocket:
          port: 27017
        intialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
       tcpsocket:
        port: 8080
       intialDelaySeconds: 15
       periodSeconds: 10
